name: huw och hans projekt
url: ""
baseurl: ""
cover: "/assets/img/cover.jpg"
logo:  "/assets/img/logo.png"
email: hugohoover.denovo@gmail.com
twitter_username: HuwHoover
github_username: hugohoover

markdown: kramdown
highlighter: rouge

exclude:
  - "_bak"
  - "_origin"
  - "_sources"
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - _dev
  - org

future: true
